### ISSUE TITLE
Not accepting decryption key

### ISSUE THREAD

**Issue by pr0xychain** [alextusinean/es3-editor#1]
Hi, using your tool (very appreciated) I've passed in the .es3 file along with the decryption key "password" (believe it or not)

I got this key from the key variable in ES3Settings in dnspy

![image](https://github.com/alextusinean/es3-editor/assets/77388034/6be1eabd-3191-4966-81ce-3e29c684db0e)
![image](https://github.com/alextusinean/es3-editor/assets/77388034/0bad2ebe-8d23-41d1-ba11-d63418550f5b)

**Comment by alextusinean** [comment]
that's not the decryption key. It's the default one. Can you please share the game's data.unity3d/resources.assets file?

**Comment by 4bstract** [comment]
no worries bro i was able to get what i wanted in the game without the need of save editing

though for future reference could you walk me through how you would go about getting the decryption key?

**Comment by garyliu0816** [comment]
how to find decryption key from apk?

**Comment by alextusinean** [comment]
Usually I just hook an ES3 method and get it from there.
