### ISSUE TITLE
Decryption Key for "NIGHT-RUNNERS PROLOGUE"

### ISSUE THREAD

**Issue by Benno1308** [alextusinean/es3-editor#4]
Game can be found here: https://planet-jem.itch.io/night-runners-prologue | https://www.patreon.com/NightRunnersGame
Decryption Key (default key in ES3Defaults): `15IiJlm7~W`

**Comment by alextusinean** [comment]
added in 316fd394d14f5de430f37b7938b7f63a9d849f16, thank you
